import { EnterpriseHandoverReport } from './handover'

// Synthetic, prebuilt handover snapshot. It is intentionally independent of the product API.
export const demoHandoverReport: EnterpriseHandoverReport = {
  tenant_id: 'demo-tenant',
  generated_at: '2026-10-08T06:00:00.000Z',
  policy_id: 'demo-enterprise-handover-v1',
  summary: { transferred: 2, protected: 1, redacted_for_review: 1, archived: 1 },
  source_of_truth_ids: ['crm-renewal-requirement', 'policy-incident-response'],
  successor_memory_ids: ['northstar-escalation-playbook', 'acme-integration-owner'],
  successor_prompt: 'Approved company knowledge only. Personal memories and secrets are excluded.',
  items: [
    {
      memory_id: 'crm-renewal-requirement',
      content: 'Acme requires SAML SSO and SCIM provisioning before its renewal can close.',
      owner: 'company_system', transfer_policy: 'source_of_truth', business_owner: 'Revenue Operations',
      source_label: 'CRM / Acme account', source_id: 'CRM:ACME-104', classification: 'internal',
      outcome: 'retained_at_source', reason: 'The CRM remains the authoritative, read-only source.',
      trust: { score: 95, level: 'high', reason_codes: ['authoritative_source', 'verified'] },
      policy: { action: 'read_only', reason_codes: ['source_of_truth'], explanation: 'The record remains in the company CRM.' },
      eligible_for_successor: false,
    },
    {
      memory_id: 'policy-incident-response',
      content: 'Enterprise production outages must be routed to Platform On-call within 15 minutes.',
      owner: 'company_system', transfer_policy: 'source_of_truth', business_owner: 'Support Operations',
      source_label: 'Published incident policy', source_id: 'POLICY:INC-12', classification: 'internal',
      outcome: 'retained_at_source', reason: 'The published policy remains authoritative at its source.',
      trust: { score: 96, level: 'high', reason_codes: ['authoritative_source', 'verified'] },
      policy: { action: 'read_only', reason_codes: ['source_of_truth'], explanation: 'The successor can query the company policy.' },
      eligible_for_successor: false,
    },
    {
      memory_id: 'northstar-escalation-playbook',
      content: 'Northstar outage escalations use Platform On-call and include impact, owner, and next update time.',
      owner: 'company', transfer_policy: 'transfer_if_allowed', business_owner: 'Customer Success',
      source_label: 'Departing support agent', source_id: 'AGENT:DEMO-SUPPORT', classification: 'internal',
      outcome: 'transferred', reason: 'Company-owned, current operational knowledge is approved for the successor.',
      trust: { score: 88, level: 'high', reason_codes: ['company_owned', 'current'] },
      policy: { action: 'allow', reason_codes: ['company_memory', 'approved_purpose'], explanation: 'The memory is company-owned and suitable for the successor.' },
      eligible_for_successor: true,
    },
    {
      memory_id: 'acme-integration-owner',
      content: 'Enterprise Success owns Acme integration questions; coordinate the security review with Legal.',
      owner: 'team', transfer_policy: 'transfer_if_allowed', business_owner: 'Enterprise Success',
      source_label: 'Departing support agent', source_id: 'AGENT:DEMO-SUPPORT', classification: 'internal',
      outcome: 'transferred', reason: 'This team-owned routing note is relevant to successor work.',
      trust: { score: 84, level: 'high', reason_codes: ['team_owned', 'current'] },
      policy: { action: 'allow', reason_codes: ['team_memory', 'approved_purpose'], explanation: 'The memory supports continuity for the team.' },
      eligible_for_successor: true,
    },
    {
      memory_id: 'employee-private-schedule',
      content: 'Personal schedule details are protected and are not disclosed to the successor.',
      redacted_content: 'Personal availability — details protected.',
      owner: 'employee', transfer_policy: 'protect', business_owner: 'Demo employee',
      source_label: 'Private employee memory', source_id: 'AGENT:DEMO-PRIVATE', classification: 'private_employee',
      outcome: 'protected', reason: 'Private employee information stays with its owner.',
      trust: { score: null, level: 'not_scored', reason_codes: ['private_employee_data'] },
      policy: { action: 'deny', reason_codes: ['employee_owned', 'private_data'], explanation: 'Private employee memory cannot cross the handover boundary.' },
      eligible_for_successor: false,
    },
    {
      memory_id: 'mixed-customer-note',
      content: 'Customer needs a security review before renewal. [Personal preference removed for review.]',
      redacted_content: 'Customer needs a security review before renewal. [Personal preference removed for review.]',
      owner: 'company', transfer_policy: 'redact_and_review', business_owner: 'Customer Success',
      source_label: 'Departing support agent', source_id: 'AGENT:DEMO-SUPPORT', classification: 'mixed',
      outcome: 'redacted_for_review', reason: 'Mixed business and personal content is redacted and held for review.',
      trust: { score: 61, level: 'review', reason_codes: ['mixed_content', 'redaction_required'] },
      policy: { action: 'review', reason_codes: ['redact_personal_content', 'human_review'], explanation: 'A reviewer must approve the redacted content.' },
      eligible_for_successor: false,
    },
    {
      memory_id: 'stale-escalation-note',
      content: 'Legacy escalation contact list from a retired rotation.',
      owner: 'company', transfer_policy: 'transfer_if_allowed', business_owner: 'Support Operations',
      source_label: 'Historical agent memory', source_id: 'AGENT:DEMO-SUPPORT', classification: 'internal',
      outcome: 'archived', reason: 'Stale operational details are archived rather than transferred.',
      trust: { score: 34, level: 'low', reason_codes: ['stale', 'unverified'] },
      policy: { action: 'archive', reason_codes: ['stale_record'], explanation: 'The memory is too old for successor use.' },
      eligible_for_successor: false,
    },
  ],
}
